# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "retro_tes"

scenario:
  ll:
  - v1.15
  clusters:
  - 90
  sector_opts:
  - Co2L0.45-1H-dist1.05-T-H-B-I
  planning_horizons:
  - 2030

enable:
  custom_busmap: true

# reduce available transfer capacity to 50% to better account for grid internal bottlenecks due to low spatial resolution of 48 nodes
lines:
  s_max_pu: 0.5

electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc]
  powerplants_filter: DateOut >= 2030 and not Fueltype.isin(['Nuclear', 'Hard Coal', 'Lignite'])
  custom_powerplants: DateIn <= 2030 and DateOut >= 2030

energy:
  energy_totals_year: 2013

pypsa_eur:
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - solar
  - ror

biomass:
  year: 2030

sector:
  agriculture: false
  district_heating:
    progress:
      2030: 0.3
  residential_heat_dsm: true
  residential_heat_restriction_value: 0.27
  residential_heat_restriction_time: [10, 22] # 9am and 9pm
  cluster_heat_buses: false
  reduce_space_heat_exogenously: false
  retrofitting:
    retro_endogen: true
    WWHR_endogen: true
  tes: true
  boilers: false #true
  biomass_boiler: false
  micro_chp: true
  regional_coal_demand: true
  use_fischer_tropsch_waste_heat: false
  use_haber_bosch_waste_heat: false
  use_methanolisation_waste_heat: false
  use_methanation_waste_heat: false
  use_fuel_cell_waste_heat: true
  use_electrolysis_waste_heat: false
  biomass_spatial: true
  biomass_transport: true
  land_transport_fuel_cell_share:
    2030: 0.05
  land_transport_electric_share:
    2030: 0.25
  land_transport_ice_share:
    2030: 0.7
  reduce_hot_water_factor:
    2030: 0.05
  conventional_generation:
    OCGT: gas
    coal: coal
    lignite: lignite
    nuclear: uranium
  keep_existing_capacities: True

costs:
  year: 2025
  fill_values:
    "discount rate": 0.04
  fuel:
    OCGT: 38.84 # https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52022SC0230 (Annex)
    CCGT: 38.84
    gas: 38.84
    coal: 24.57 # https://businessanalytiq.com/procurementanalytics/index/subbituminous-coal-price-index/
    lignite: 22.11 # https://businessanalytiq.com/procurementanalytics/index/lignite-coal-price-index/
    nuclear: 1.75 # https://markets.businessinsider.com/commodities/uranium-price
    uranium: 1.75
  investment:
    "central solar thermal": 280650
    "decentral solar thermal": 428920
  lifetime:
    "central solar thermal": 30
    "decentral solar thermal": 30

adjustments:
  sector: {"p_nom_max": {"solar rooftop": 1.095}}

solving:
  options:
    assign_all_duals: true
  solver_options:
    gurobi-default:
      threads: 8
      BarConvTol: 1.e-4
