# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "flexible"

scenario:
  ll:
  - v1.3
  clusters:
  - 48
  sector_opts:
  - Co2L0.1-12H-T-H-B-I
  planning_horizons:
  - 2040

enable:
  custom_busmap: true

# reduce available transfer capacity to 50% to better account for grid internal bottlenecks due to low spatial resolution of 48 nodes
lines:
  s_max_pu: 0.5

electricity:
  powerplants_filter: DateOut >= 2040 and not Fueltype == 'Nuclear'
  custom_powerplants: DateIn <= 2040 and DateOut >= 2040

energy:
  energy_totals_year: 2013

biomass:
  year: 2040

sector:
  agriculture: false
  district_heating:
    progress:
      2040: 0.6
  residential_heat_dsm: true
  residential_heat_restriction_value: 0.2
  cluster_heat_buses: false
  retrofitting:
    retro_endogen: true 
  tes: true
  boilers: true
  biomass_boiler: false
  micro_chp: true
  regional_coal_demand: true
  use_fischer_tropsch_waste_heat: false
  use_haber_bosch_waste_heat: false
  use_methanolisation_waste_heat: false
  use_methanation_waste_heat: false
  use_fuel_cell_waste_heat: true
  use_electrolysis_waste_heat: false
  biomass_spatial: true
  biomass_transport: true
  land_transport_fuel_cell_share:
    2040: 0.1
  land_transport_electric_share:
    2040: 0.6
  land_transport_ice_share:
    2040: 0.3
  reduce_hot_water_factor:
    2040: 0.2

costs:
  year: 2035
  fill_values:
    "discount rate": 0.04

solving:
  options:
    assign_all_duals: true
  solver_options:
    gurobi-default:
      threads: 8
      BarConvTol: 1.e-4
