# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

run:
  name: "rigid"

foresight: overnight

planning_horizons:
- 2050

# reduce available transfer capacity to 50% to better account for grid internal bottlenecks due to low spatial resolution of 48 nodes
lines:
  s_max_pu: 0.5

co2_budget:
  relative: true
  upper:
    2020: 0.725
    2030: 0.45
    2040: 0.1
    2050: 0.0

electricity:
  base_network: entsoegridkit
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc]
  powerplants_filter: DateOut >= 2050 and not Fueltype.isin(['Nuclear', 'Hard Coal', 'Lignite'])
  custom_powerplants: DateIn <= 2050 and DateOut >= 2050
  transmission_limit: v1.5

energy:
  energy_totals_year: 2013

pypsa_eur:
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - solar
  - ror

sector:
  agriculture: false
  district_heating:
    progress:
      2050: 1.0
  residential_heat:
    dsm:
      enable: false
  cluster_heat_buses: false
  reduce_space_heat_exogenously: false
  retrofitting:
    retro_endogen: false
    WWHR_endogen: false
  tes: false # true
  boilers: false #true
  biomass_boiler: false
  chp:
    micro_chp: true
  regional_coal_demand: true
  use_fischer_tropsch_waste_heat: false
  use_haber_bosch_waste_heat: false
  use_methanolisation_waste_heat: false
  use_methanation_waste_heat: false
  use_fuel_cell_waste_heat: true
  use_electrolysis_waste_heat: false
  biomass_spatial: true
  biomass_transport: true
  bev_dsm: false
  land_transport_fuel_cell_share:
    2050: 0.15
  land_transport_electric_share:
    2050: 0.85
  land_transport_ice_share:
    2050: 0
  reduce_hot_water_factor:
    2050: 0
  conventional_generation:
    CCGT: gas
    coal: coal
    lignite: lignite
    nuclear: uranium
  keep_existing_capacities: True
  electricity_distribution_grid: true

biomass:
  year: 2050
  share_unsustainable_use_retained:
    2020: 0
    2030: 0
    2040: 0
    2050: 0
  share_sustainable_potential_available:
    2020: 1
    2030: 1
    2040: 1
    2050: 1.2

costs:
  year: 2045
  fill_values:
    "discount rate": 0.04

clustering:
  mode: custom_busmap
  cluster_network:
    n_clusters: 48
  temporal:
    averaging: 1h

adjustments:
  sector:
    factor:
      Link:
        electricity distribution grid:
          capital_cost: 2.0
      Generator:
        solar rooftop:
          p_nom_max: 1.134 # https://www.epj-pv.org/articles/epjpv/full_html/2024/01/pv230071/pv230071.html
    absolute: false

solving:
  options:
    assign_all_duals: true
  solver_options:
    gurobi-default:
      threads: 8
      BarConvTol: 1.e-4
      BarHomogeneous: 1
